### ISSUE TITLE
Generate keywords

### ISSUE THREAD

**Issue by baptisteArno** [leodr/generate-emoji-list#1]
Hey @leodr, great work on this package.

It would be awesome to populate the data with keywords that would help to better search for emojis.

I found [emoji-data](https://github.com/Mange/emoji-data) that does exactly this using CLDR dataset.

Would you be OK to migrate to this dataset in order to have these precious keywords? I can work on a PR.

**Comment by baptisteArno** [comment]
To explain a bit more, your package is used on the [Emoji Raycast extension](https://github.com/raycast/extensions) and it lacks some predictability sometimes.

Example:
<img width="802" alt="CleanShot 2021-12-24 at 10 33 42@2x" src="https://user-images.githubusercontent.com/16015833/147340524-96fd900a-1bb7-446a-8d23-ea92c602a51d.png">

I would expect to have at least one "shocked" emoji, right?

**Comment by baptisteArno** [comment]
[Here is a sample of the data](https://github.com/unicode-org/cldr-json/blob/40.0.0/cldr-json/cldr-annotations-modern/annotations/en/annotations.json)

Search for "shocked"

**Comment by leodr** [comment]
> To explain a bit more, your package is used on the [Emoji Raycast extension](https://github.com/raycast/extensions) and it lacks some predictability sometimes.
> 
> 
> 
> Example:
> 
> <img width="802" alt="CleanShot 2021-12-24 at 10 33 42@2x" src="https://user-images.githubusercontent.com/16015833/147340524-96fd900a-1bb7-446a-8d23-ea92c602a51d.png">
> 
> 
> 
> I would expect to have at least one "shocked" emoji, right?
> 
> 

That's cool, love seeing it in use there!

I'd be open to expanding the data with keywords, but I wouldn't like to deviate from the official source, maybe we could merge in the keywords from the list you provided just like we currently do with the GitHub shortcuts?

**Comment by baptisteArno** [comment]
> I'd be open to expanding the data with keywords, but I wouldn't like to deviate from the official source, maybe we could merge in the keywords from the list you provided just like we currently do with the GitHub shortcuts?

Yeah, that's definitely the way to do this. Are you interested in digging in or should I give it a spin?

**Comment by leodr** [comment]
> > I'd be open to expanding the data with keywords, but I wouldn't like to deviate from the official source, maybe we could merge in the keywords from the list you provided just like we currently do with the GitHub shortcuts?
> 
> 
> 
> Yeah, that's definitely the way to do this. Are you interested in digging in or should I give it a spin?

Im on holiday right now, but I could review your PR and release a new version if you want to implement this feature.
